### ISSUE TITLE
hey hey

### ISSUE THREAD

**Issue by BigBr000** [M47Hs/godsunchained#4]

**Comment by BigBr000** [comment]
And discounts working ?

**Comment by enitrat** [comment]
Hey,
The project is no longer under development but is still working. As it was my first project with React, UI and UX are not really great.
You can still try it, there is a live version at https://gumarkets.herokuapp.com/#/
Discounts are not working anymore, as they have become irrelevant since last July.
I still use it to track wallets and have details about price history

**Comment by BigBr000** [comment]
sad that discounts not working, that we catch something, because people have bots and buying all cheap cards...

**Comment by enitrat** [comment]
Yeah but the discount section is no longer useful given that there now are plenty of bots

**Comment by BigBr000** [comment]
yes i know there alot of bots :P  but maybe you know where can i find script for market that shows me discounts ?

**Comment by BigBr000** [comment]
how hard is to get bot for market to try luck ? because 1 person have alot bots.
